### ISSUE TITLE
Incompatability between "Shield Mechanics" and "Tetra"

### ISSUE THREAD

**Issue by Kazzc** [someaddons/Shieldmechanics#8]
**Describe the bug**
So when blocking with a tetra shield against illager vindicators or crossbow bolts it will just crash your game.

**To Reproduce**
Wear a tetra shield.
Block an attack from an illager
Crash game.

**Expected behavior**
Not crash the game. . .

** Mod version **
1.16.5

-- Entity being ticked --
Details:
	Entity Type: minecraft:vindicator (net.minecraft.entity.monster.VindicatorEntity)
	Entity ID: 33519
	Entity Name: Vindicator
	Entity's Exact location: 148.93, 69.00, -232.02
	Entity's Block location: World: (148,69,-233), Chunk: (at 4,4,7 in 9,-15; contains blocks 144,0,-240 to 159,255,-225), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: -0.12, -0.08, -0.08
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: Cannot invoke "net.minecraft.entity.Entity.toString()" because the return value of "net.minecraft.entity.Entity.func_184187_bx()" is null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:observerlib:coremodmethod,xf:fml:astralsorcery:sun_brightness_server,xf:fml:twilightforest:hitbox,pl:mixin:APP:sereneseasons.mixins.json:MixinWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:betternether.mixins.json:ServerWorldMixin,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:endergetic.mixins.json:ServerWorldMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:entity.MobServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}

**Comment by Kazzc** [comment]
How hard will it be to add a mod blacklist where ``Shield Mechanics`` does not edit their stats.

**Comment by someaddons** [comment]
can't reproduce the crash, next time upload it to a proper paste site, so I can read the full report
